Causes
2021-12-18 18:32:51.682 22183-22332/com.snijsure.workmanagerupgrade E/WM-WorkerFactory: Invalid class: com.snijsure.workmanagerupgrade.SampleWorker
    java.lang.ClassNotFoundException: com.snijsure.workmanagerupgrade.SampleWorker
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:88)
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245)
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.snijsure.workmanagerupgrade.SampleWorker" on path: DexPathList[[zip file "/data/app/~~eo9ByC_W0dTPi-b-s3WE-Q==/com.snijsure.workmanagerupgrade-fygyCncsiq--jimMX7LEWw==/base.apk"],nativeLibraryDirectories=[/data/app/~~eo9ByC_W0dTPi-b-s3WE-Q==/com.snijsure.workmanagerupgrade-fygyCncsiq--jimMX7LEWw==/lib/arm64, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at androidx.work.WorkerFactory.createWorkerWithDefaultFallback(WorkerFactory.java:88) 
        at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:245) 
        at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137) 
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
2021-12-18 18:32:51.682 22183-22332/com.snijsure.workmanagerupgrade E/WM-WorkerWrapper: Could not create Worker com.snijsure.workmanagerupgrade.SampleWorker